---
title: "OOP en clase S4 en base a los algoritmos de Convolución"
author: "Jesús Cóndor"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Indice

   1. Introducción. 

   2. Estado del arte.

   3. Diseño del experimento.

   4. Experimentos y resultados.

   5. Discusión

   6. Conclusiones.

   7. Bibliografía


## Introducción

En las últimas décadas la programación y las matemáticas han ido desarrollando una interacción muy fuerte de modo que hoy en día se puede decir que la matemática necesita a la programación y la programación necesita de las matemáticas ya sea para cálculos, simulaciones, gráficos, etc. Dentro de las matemáticas tenemos lo que es la probabilidad y la estadística que concierne básicamente en la incertidumbre de cierto evento o suceso que pueda ocurrir en base a ciertos datos recopilados o sino definir una variable aleatoria y trabajar con ella bajo cierto espacio muestral. En esta oportunidad utilizaremos las propiedades de las variables aleatorias y nos enfocaremos en la transformaciones de esta y como esto puede ser llevado a la programación.

La "Programación orientado a objetos" (OOP) nos ayuda grandemente en la implementación de convolución de distribuciones de variables aleatorias de valor real (discretas o continuas). Por tanto es bueno observar las características de la **OOP** y darle un soporte en base a los algoritmos de convolución que nos ayuda mucho en el análisis probabilístico, como por ejemplo en las transformaciones de **funciones**, en este caso las transformaciones de variables aleatorias y esto llevarlo a la programación en clase S4.

En esta oportunidad el lenguaje de programación que utilizaremos sera el lenguaje R, que nos ayudara en la parte de los _gráficos_ y tambien de _cálculos_. Ademas trataremos los siguientes puntos:

* Programación orientada a objetos para distribuciones de probabilidad.

* La clase S4.

* Implementación de las clases de distribuciones dentro del concepto S4.

* El algoritmo de convolución y FFT.

* Algoritmos basados en DFT(Transformación Discreta de Fourier).

## Estado Del Arte


La convolución de las distribuciones de probabilidad surge en la teoría de la probabilidad y la estadística como la operación en términos de distribuciones de probabilidad que corresponde a la adición de variables aleatorias independientes y por extensión, a la formación de combinaciones lineales de variables aleatorias. 

Para su implementación, el uso de la Transformada Rápida de Fourier(FFT) ha sido muy común desde la aparición del algoritmo de Cooley y Tukey, el cual es un algoritmo eficiente que ayuda a calcular la Transformada de Fourier Discreta(DFT) y su inversa.
Las apariciones de arquitecturas informáticas paralelas dan más importancia al uso de la FFT, en contraste con la convolución mediante cálculos directos y si sumamos a esto un enfoque de Programación Orientada a Objetos (POO) hace que esta técnica sea aún más atractiva ya que podemos usarla como un algoritmo predeterminado en situaciones donde no existe una alternativa mejor, mientras que en casos especiales como por ejemplo , las variables aleatorias normales o de Poisson, donde la convolución se reduce a la transformación de los parámetros correspondientes.

En este contexto, la convolución es un arma potente para establecer una aritmética completa de operaciones matemáticas que actúan sobre objetos de distribución, que comprende, entre otros, operadores +, -, *, / y ^. En esta aritmética, identificamos distribuciones con variables aleatorias independientes: si X1 y X2 son variables de aleatorias independiente, X1 + X2 producirá la distribución de la suma de variables aleatorias (independientes) respectivas, es decir, su convolución. Técnicamente, hablando en términos de programación, hemos sobrecargado el operador + para distribuciones univariables. La propia convolución se calcula de acuerdo con las clases reales de los operandos, con métodos particulares (exactos) para, por ejemplo, distribuciones normales o de Poisson.



